namespace EitHost.Core.Diagnostics;

public sealed record DdsTimingSmokeReport(
    DateTimeOffset StartedAt,
    DateTimeOffset FinishedAt,
    bool ExecuteRequested,
    bool Ready,
    bool Passed,
    string Status,
    DdsTimingSmokeOptions Options,
    IReadOnlyList<DdsTimingSmokeCaseReport> Cases,
    IReadOnlyList<string> Blockers,
    IReadOnlyList<string> Warnings);

public sealed record DdsTimingSmokeCaseReport(
    double RequestedChannelCycles,
    uint RequestedTimeUs,
    string FirmwareVersion,
    byte FirmwareProtocolVersion,
    uint TimerClockHz,
    ushort TimerTicks,
    double EffectiveTimeUs,
    double EffectiveChannelCycles,
    ushort SwitchGuardMinimumUs,
    string RequestHex,
    string AcknowledgementHex,
    double ExpectedWindowSamples,
    double ObservedWindowSamples,
    double TimingToleranceSamples,
    bool TimingMatched,
    double MeasuredCarrierHz,
    double CarrierErrorPercent,
    IReadOnlyList<int> ObservedStepOrder,
    bool StepOrderMatched,
    int StrictAcceptedFrames,
    int RejectedFrames,
    int RequiredStrictFrames,
    int ValidTop3Windows,
    int TotalWindows,
    bool StrictQualityPassed,
    string RawHdf5Path,
    string RawHdf5Sha256,
    string DemodHdf5Path,
    string DemodHdf5Sha256,
    string AckJsonPath,
    string AckJsonSha256,
    bool Passed,
    string? Failure);
